query About($siteId: String, $locale: SiteLocale = sv) {
	about(
		locale: $locale
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		intro
		media {
			...MediaFragment
		}
		content {
			... on AboutBlockRecord {
				__typename
				id
				headline
				text {
					blocks {
						__typename
						... on ButtonBlockRecord {
							id
							url
							text
							openInNewWindow
						}
					}
					links
					value
				}
				media {
					...MediaFragment
				}
			}
		}
	}
}
