query About($siteId: String, $locale: SiteLocale = sv) {
	about(
		locale: $locale
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		content {
			blocks
			links
			value
		}
	}
}
