query Contact($siteId: String, $locale: SiteLocale = sv) {
	contact(
		locale: $locale
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		text {
			links
			blocks
			value
		}
		email
		seller1
		seller2
	}
}
