query Offer($siteId: String, $locale: SiteLocale = sv) {
	offer(
		locale: $locale
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		content {
			blocks
			links
			value
		}
		image {
			...ImageFragment
		}
	}
}

query AllOfferCategories($siteId: String, $locale: SiteLocale = sv) {
	allOfferCategories(
		locale: $locale
		first: 100
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		slug
		_allReferencingOfferItems(
			first: 100
			locale: $locale
			filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
		) {
			...OfferItemFragment
		}
	}
}
query OfferCategory($slug: String, $locale: SiteLocale = sv) {
	offerCategory(locale: $locale, filter: { slug: { eq: $slug } }) {
		id
		title
	}
}

query OfferItemsByCategory($categoryId: ItemId, $locale: SiteLocale = sv) {
	allOfferItems(locale: $locale, first: 100, filter: { category: { eq: $categoryId } }) {
		...OfferItemFragment
	}
}

query AllOfferItems($locale: SiteLocale = sv) {
	allOfferItems(locale: $locale, first: 100) {
		...OfferItemFragment
	}
}

fragment OfferItemFragment on OfferItemRecord {
	id
	title
	category {
		id
		title
	}
	subtitle
	content {
		blocks {
			__typename
			... on ButtonBlockRecord {
				id
				text
				url
			}
		}
		links
		value
	}
	gallery {
		id
		media {
			...OfferMediaFragment
		}
	}
	backgroundColor {
		hex
		red
		green
		blue
	}
	backgroundImage {
		...ImageFragment
	}
}
