query Start($siteId: String, $locale: SiteLocale = sv) {
	start(
		locale: $locale
		filter: { siteSelector: { any: { siteSelector: { siteId: { eq: $siteId } } } } }
	) {
		id
		title
		content {
			__typename
			... on FullscreenMediaBlockRecord {
				title
				text
				media {
					...MediaFragment
				}
			}
			... on OfferBlockRecord {
				id
				title
				categories {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
			}
		}
		aboutHeadline
		aboutText {
			links
			blocks
			value
		}
		aboutImage {
			...ImageFragment
		}
		siteSelector {
			siteId
		}
	}
}
